authors:
  # Identificador único del autor (ej: nombre de usuario)
  Rasty94:
    name: "rasty94"
    description: "Admin"
    avatar: "https://avatars.githubusercontent.com/u/18195312?v=4"  # o URL externa
    url: "https://github.com/rasty94"  # opcional
