authors:
  # Identificador único del autor (ej: nombre de usuario)
  Admin1:
    name: "Admin1"
    description: "Admin"
    avatar: "ruta/imagen-perfil.png"  # o URL externa
    url: "https://enlace-perfil.com"  # opcional
